# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-21 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '__first__'),
        ('filedetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmap',
            name='user',
        ),
        migrations.RemoveField(
            model_name='urlprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='urlmap',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Document'),
        ),
        migrations.AddField(
            model_name='urlprofile',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Document'),
        ),
    ]
