# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '__first__'),
        ('filedetail', '0002_auto_20181221_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('max_urls', models.IntegerField(default=-1)),
                ('max_concurrent_urls', models.IntegerField(default=100)),
                ('default_lifespan', models.IntegerField(default=120)),
                ('default_max_uses', models.IntegerField(default=-1)),
                ('document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Document')),
            ],
        ),
        migrations.RemoveField(
            model_name='urlprofile',
            name='document',
        ),
        migrations.AlterField(
            model_name='urlmap',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Document'),
        ),
        migrations.DeleteModel(
            name='UrlProfile',
        ),
    ]
