# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedetail', '0003_auto_20181223_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmap',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
