# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedetail', '0004_urlmap_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='enabled',
            field=models.CharField(max_length=5),
        ),
    ]
