# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-28 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedetail', '0005_auto_20181224_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprofile',
            name='document',
        ),
        migrations.AddField(
            model_name='urlmap',
            name='webhook',
            field=models.URLField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name='DocProfile',
        ),
    ]
