# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-28 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedetail', '0006_auto_20181228_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='webhook',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
